version: "3"

services:
  fileserver:
    container_name: fileserver
    image: fileserver:devel
    build: .
    tty: true
    command: uvicorn --host 0.0.0.0 --port 80 fileserver.app:app --reload
    volumes:
      - ./fileserver:/fileserver/fileserver
      - ./db:/db:rw
      # - /data/to/mount:/data:ro
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      DB_PATH: /db/file_hash.db
    ports:
      - 80:80

  redis:
    image: redis

  worker:
    container_name: worker
    image: fileserver:devel
    tty: true
    command: celery -A fileserver.crawler worker -l INFO
    volumes:
      - ./fileserver:/fileserver/fileserver
      - ./db:/db:rw
      # - /data/to/mount:/data:ro
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      DB_PATH: /db/file_hash.db
    depends_on:
      - redis

  flower:
    container_name: flower
    image: fileserver:devel
    tty: true
    command: celery --broker=redis://redis:6379 flower
    ports:
      - 5555:5555
    depends_on:
      - redis
